### PR TITLE
Next iteration

### PR DESCRIPTION
**Pull request by jasnell**
Next iteration... WIP

### CODE REVIEW

**Comment by jasnell** [comment]
@nodejs/quic... the further along things get here, the more obvious it is that we'll need better handling of the outbound data buffer. What's here works ok but it's has issues and there's at least one bug that I need to track down when the data to send is too large.

**Comment by splitice** [comment]
FYI

There is some implicit typecasting happening with SetConfig on 64bit, and on 32bit failures to compile. `max_crypto_buffer_` is size_t not uint64_t.

```
‘uint64_t* {aka long long unsigned int*}’ for argument ‘3’ to ‘void node::quic::{anonymous}::SetConfig(node::Environment*, int, uint64_t*)’
```

**Comment by jasnell** [comment]
There's a lot in this PR. I'm working on fixing one fun little timing bug then will get this landed

**Comment by splitice** [comment]
I see my report is fixed with e23f91f4209f408551fa20094bc949f575ff3d98 👍

**Comment by jasnell** [comment]
Ok, so... current status on this... there are still a number of internal state issues that are gumming up the works on this. The issue has to do with when the QuicSession and QuicStream instances are shut down and the timing of corresponding state changes and the need to Ack every packet. I'm still working through that but I don't want to keep this PR open much longer given that there are lots of other fixes/changes in here.

**Comment by jasnell** [comment]
ugh... got things working on Windows. Not working on Ubuntu now. Had it working on Ubuntu but it broke on Windows. Sigh. Very close to having this iteration done but it's taking just a bit longer.

**Comment by jasnell** [comment]
Ok, this is still a bit broken but I'm going to get it landed. I'm going to be away from the laptop for about 5 days starting tomorrow for some personal time off and just can't keep blocking on this.

Where this is broken is around the buffer management, timing of acks, and session/stream teardown. I'm going to get this PR landed and keep working it but the fix will likely need to wait until I'm back from PTO.

**Comment by jasnell** [comment]
Here's the work in progress patch I'm working through in case someone wants to work on it while I'm out...

```
From 6b5a899a36b3a30fa07861af3566c122e4876706 Mon Sep 17 00:00:00 2001
From: James M Snell <jasnell@gmail.com>
Date: Mon, 1 Jul 2019 10:57:51 -0700
Subject: [PATCH] quic: fixup writes

---
 lib/internal/quic/core.js                     |   4 +-
 src/node_quic_buffer.h                        | 208 ++++++------------
 src/node_quic_session.cc                      |  29 ++-
 src/node_quic_session.h                       |   1 -
 src/node_quic_socket.cc                       |  17 +-
 src/node_quic_stream.cc                       |  34 ++-
 src/node_quic_stream.h                        |   2 +-
 test/cctest/test_quic_buffer.cc               |  83 ++-----
 test/parallel/test-quic-stream-close-early.js |  64 +++---
 9 files changed, 146 insertions(+), 296 deletions(-)

diff --git a/lib/internal/quic/core.js b/lib/internal/quic/core.js
index 4362c85e86..62cd004118 100644
--- a/lib/internal/quic/core.js
+++ b/lib/internal/quic/core.js
@@ -388,7 +388,7 @@ function onStreamClose(id, appErrorCode) {
   this[owner_symbol][kStreamClose](id, appErrorCode);
 }
 
-function onStreamReset() {
+function onStreamReset(appErrorCode, finalSize) {
   this[owner_symbol][kStreamReset](appErrorCode, finalSize);
 }
 
@@ -1850,7 +1850,7 @@ class QuicStream extends Duplex {
 
     // Finally, emit the abort event.
     if (this.#aborted)
-      this.emit('abort', code, family);
+      process.nextTick(emit.bind(this, 'abort', code, family));
   }
 
   get aborted() {
diff --git a/src/node_quic_buffer.h b/src/node_quic_buffer.h
index 6964c60c23..31090f0101 100644
--- a/src/node_quic_buffer.h
+++ b/src/node_quic_buffer.h
@@ -18,12 +18,9 @@
 namespace node {
 namespace quic {
 
-// QuicBuffer an internal linked list of uv_buf_t instances
-// representing data that is to be sent. All data in the
-// Buffer has to be retained until it is Consumed or Canceled.
-// For QUIC, the data is not consumed until an explicit ack
-// is received or we know that we do not need the data.
-
+// The done callback is invoked when a given batch of data has been consumed.
+// This occurs when all of the data within a batch has been serialized to
+// frames, regardless of whether those frames have been transmitted yet or not.
 typedef std::function<void(int status, void* user_data)> done_cb;
 
 // Default non-op done handler.
@@ -93,60 +90,20 @@ struct quic_buffer_chunk : public MemoryRetainer {
 };
 
 // A QuicBuffer is a linked-list of quic_buffer_chunk instances.
-// There are three significant pointers: root_, head_, and tail_.
-//   * root_ is the base of the linked list
-//   * head_ is a pointer to the current read position of the linked list
-//   * tail_ is a pointer to the current write position of the linked list
-// Items are dropped from the linked list only when either Consume() or
-// Cancel() is called. Consume() will consume a given number of bytes up
-// to, but not including the read head_. Cancel() will consume all remaining
-// bytes in the linked list. As whole quic_buffer_chunk instances are
-// consumed, the corresponding Done callback will be invoked, allowing
-// any memory to be freed up.
-//
-// Use SeekHead(n) to advance the read head_ forward n positions.
-//
-// DrainInto() will drain the remaining quic_buffer_chunk instances
-// into a vector and will advance the read head_ to the end of the
-// QuicBuffer. The function will return the number of positions drained
-// which would then be passed to SeekHead(n) to advance the read head.
-//
-// QuicBuffer supports move assignment that will completely reset the source.
-// That is,
-//  QuicBuffer buf1;
-//  QuicBuffer buf2;
-//  buf2 = std::move(buf1);
-//
-// Will reset the state of buf2 to that of buf1, then reset buf1
-//
-// There is also an overloaded += operator that will append the source
-// content to the destination and reset the source.
-// That is,
-//  QuicBuffer buf1;
-//  QuicBuffer buf2;
-//  buf2 += std::move(buf1);
-//
-// Will append the contents of buf1 to buf2, then reset buf1
 class QuicBuffer : public MemoryRetainer {
  public:
   inline QuicBuffer() :
     head_(nullptr),
     tail_(nullptr),
     size_(0),
-    count_(0),
     length_(0) {}
 
   inline QuicBuffer(QuicBuffer&& src) noexcept :
-    head_(src.head_),
+    head_(std::move(src.head_)),
     tail_(src.tail_),
     size_(src.size_),
-    count_(src.count_),
     length_(src.length_) {
-    root_ = std::move(src.root_);
-    src.head_ = nullptr;
-    src.tail_ = nullptr;
-    src.size_ = 0;
-    src.length_ = 0;
+    src.Reset();
   }
 
   QuicBuffer& operator=(QuicBuffer&& src) noexcept {
@@ -159,33 +116,27 @@ class QuicBuffer : public MemoryRetainer {
       // If this thing is empty, just do a move...
       this->~QuicBuffer();
       return *new(this) QuicBuffer(std::move(src));
-    } else {
-      tail_->next = std::move(src.root_);
-      // If head_ is null, then it had been read to the
-      // end, set the new head_ equal to the appended
-      // root.
-      if (head_ == nullptr)
-        head_ = tail_->next.get();
+    } else if (src.head_) {
+      // Only proceed if src has a head_
+      CHECK_NOT_NULL(src.tail_);
+
+      tail_->next = std::move(src.head_);
       tail_ = src.tail_;
       length_ += src.length_;
       size_ += src.size_;
-      count_ += src.size_;
-      src.head_ = nullptr;
-      src.tail_ = nullptr;
-      src.size_ = 0;
-      src.length_ = 0;
-      return *this;
+      src.Reset();
     }
+    return *this;
   }
 
   inline ~QuicBuffer() override {
-    Cancel();  // Cancel the remaining data
+    Cancel();  // Cancel all remaining data
     CHECK_EQ(length_, 0);
+    CHECK_EQ(size_, 0);
   }
 
-  inline uint64_t Copy(
-      uv_buf_t* bufs,
-      size_t nbufs) {
+  // Push a copy of the given data buffers into the QuicBuffer.
+  inline uint64_t Copy(uv_buf_t* bufs, size_t nbufs) {
     uint64_t total = 0;
     for (size_t n = 0; n < nbufs; n++) {
       MallocedBuffer<uint8_t> data(bufs[n].len);
@@ -210,9 +161,7 @@ class QuicBuffer : public MemoryRetainer {
       void* user_data = nullptr,
       v8::Local<v8::Object> keep_alive = v8::Local<v8::Object>()) {
     uint64_t len = 0;
-    if (nbufs == 0 ||
-        bufs == nullptr ||
-        EMPTY_BUF(bufs[0])) {
+    if (nbufs == 0 || bufs == nullptr || EMPTY_BUF(bufs[0])) {
       done(0, user_data);
       return 0;
     }
@@ -270,55 +219,37 @@ class QuicBuffer : public MemoryRetainer {
     return size_;
   }
 
-  // The number of buffers remaining to be read
-  inline size_t ReadRemaining() {
-    return count_;
-  }
-
   // Drain the remaining buffers into the given vector.
-  // The function will return the number of positions the
-  // read head_ can be advanced.
-  inline size_t DrainInto(
-      std::vector<uv_buf_t>* list,
-      uint64_t* length = nullptr) {
-    size_t len = 0;
-    bool seen_head = false;
-    quic_buffer_chunk* pos = head_;
-    if (pos == nullptr)
-      return 0;
-    if (length != nullptr) *length = 0;
+  // The function returns the total number of bytes.
+  inline uint64_t DrainInto(std::vector<uv_buf_t>* list) {
+    uint64_t length = 0;
+    if (!head_)
+      return length;
+    auto pos = head_.get();
     while (pos != nullptr) {
       size_t datalen = pos->buf.len - pos->offset;
-      if (length != nullptr) *length += datalen;
-      list->push_back(
-          uv_buf_init(pos->buf.base + pos->offset, datalen));
-      if (pos == head_) seen_head = true;
-      if (seen_head) len++;
+      length += datalen;
+      list->push_back(uv_buf_init(pos->buf.base + pos->offset, datalen));
       pos = pos->next.get();
     }
-    return len;
+    return length;
   }
 
-  inline size_t DrainInto(
-      std::vector<ngtcp2_vec>* list,
-      uint64_t* length = nullptr) {
-    size_t len = 0;
-    bool seen_head = false;
-    quic_buffer_chunk* pos = head_;
-    if (pos == nullptr)
-      return 0;
-    if (length != nullptr) *length = 0;
+  // Drain the remaining buffers into the given vector.
+  // The function returns the total number of bytes.
+  inline uint64_t DrainInto(std::vector<ngtcp2_vec>* list) {
+    uint64_t length = 0;
+    if (!head_)
+      return length;
+    auto pos = head_.get();
     while (pos != nullptr) {
       size_t datalen = pos->buf.len - pos->offset;
-      if (length != nullptr) *length += datalen;
       list->push_back(ngtcp2_vec{
           reinterpret_cast<uint8_t*>(pos->buf.base) + pos->offset,
           datalen});
-      if (pos == head_) seen_head = true;
-      if (seen_head) len++;
       pos = pos->next.get();
     }
-    return len;
+    return length;
   }
 
   // Returns the current read head or an empty buffer if
@@ -331,22 +262,6 @@ class QuicBuffer : public MemoryRetainer {
         head_->buf.len - head_->offset);
   }
 
-  // Moves the current read head forward the given
-  // number of buffers. If amount is greater than
-  // the number of buffers remaining, move to the
-  // end, and return the actual number advanced.
-  inline size_t SeekHead(size_t amount = 1) {
-    size_t n = 0;
-    size_t amt = amount;
-    while (head_ && amt > 0) {
-      head_ = head_->next.get();
-      n++;
-      amt--;
-      count_--;
-    }
-    return n;
-  }
-
   void MemoryInfo(MemoryTracker* tracker) const override {
     tracker->TrackFieldWithSize("length", length_);
   }
@@ -354,17 +269,21 @@ class QuicBuffer : public MemoryRetainer {
   SET_SELF_SIZE(QuicBuffer);
 
  private:
+  void Reset() {
+    head_.reset();
+    tail_ = nullptr;
+    size_ = 0;
+    length_ = 0;
+  }
+
   inline void Push(quic_buffer_chunk* chunk) {
     size_++;
-    count_++;
     if (!tail_) {
-      root_.reset(chunk);
-      head_ = tail_ = root_.get();
+      head_.reset(chunk);
+      tail_ = head_.get();
     } else {
       tail_->next.reset(chunk);
       tail_ = tail_->next.get();
-      if (!head_)
-        head_ = tail_;
     }
   }
 
@@ -381,16 +300,14 @@ class QuicBuffer : public MemoryRetainer {
   }
 
   inline bool Pop(int status = 0) {
-    if (!root_)
-      return false;
-    std::unique_ptr<quic_buffer_chunk> root(std::move(root_));
-    root_ = std::move(root.get()->next);
+    if (!head_)
+      return false;  // Nothing to do?
+    std::unique_ptr<quic_buffer_chunk> root(std::move(head_));
+    head_ = std::move(root->next);
     size_--;
 
-    if (head_ == root.get())
-      head_ = root_.get();
     if (tail_ == root.get())
-      tail_ = root_.get();
+      tail_ = head_.get();
 
     root->Done(status);
     return true;
@@ -398,17 +315,18 @@ class QuicBuffer : public MemoryRetainer {
 
   inline void Consume(int status, ssize_t amount) {
     uint64_t amt = std::min(amount < 0 ? length_ : amount, length_);
-    while (root_ && amt > 0) {
-      auto root = root_.get();
-      // Never allow for partial consumption of head when using a
-      // non-cancel status
-      if (status == 0 && head_ == root)
-        break;
-      size_t len = root->buf.len - root->offset;
+    while (head_ && amt > 0) {
+      auto head = head_.get();
+      size_t len = head->buf.len - head->offset;
+      // If the remaining length of the current chunk
+      // is greater than the amount we are consuming,
+      // increment the current chunk offset and return.
+      // Otherwise, decrement length and amt, pop the
+      // current head and continue.
       if (len > amt) {
         length_ -= amt;
-        root->offset += amt;
-        break;
+        head->offset += amt;
+        return;
       }
       length_ -= len;
       amt -= len;
@@ -416,12 +334,10 @@ class QuicBuffer : public MemoryRetainer {
     }
   }
 
-  std::unique_ptr<quic_buffer_chunk> root_;
-  quic_buffer_chunk* head_;  // Current Read Position
-  quic_buffer_chunk* tail_;  // Current Write Position
-  size_t size_;
-  size_t count_;
-  uint64_t length_;
+  std::unique_ptr<quic_buffer_chunk> head_;  // Current Read Position
+  quic_buffer_chunk* tail_;                  // Current Write Position
+  size_t size_;                              // Total number of chunks
+  uint64_t length_;                          // Total number of bytes
 };
 
 }  // namespace quic
diff --git a/src/node_quic_session.cc b/src/node_quic_session.cc
index 0f58bc3250..4d7f9fb785 100644
--- a/src/node_quic_session.cc
+++ b/src/node_quic_session.cc
@@ -453,10 +453,10 @@ int QuicSession::DoHandshakeWriteOnce() {
   return SendPacket();
 }
 
-void QuicSession::ExtendMaxStreamData(
-    int64_t stream_id,
-    uint64_t max_data) {
-  // TODO(@jasnell): Extend max stream data
+void QuicSession::ExtendMaxStreamData(int64_t stream_id, uint64_t max_data) {
+  QuicStream* stream = FindStream(stream_id);
+  if (stream != nullptr)
+    SendStreamData(stream);
 }
 
 int QuicSession::ExtendMaxStreams(bool bidi, uint64_t max_streams) {
@@ -872,8 +872,9 @@ int QuicSession::Send0RTTStreamData(
   ssize_t ndatalen = 0;
 
   std::vector<ngtcp2_vec> vec;
-  size_t count = stream->DrainInto(&vec);
-  size_t c = count;
+  stream->DrainInto(&vec);
+
+  size_t c = vec.size();
   ngtcp2_vec* v = vec.data();
 
   for (;;) {
@@ -908,8 +909,10 @@ int QuicSession::Send0RTTStreamData(
     if (nwrite == 0)
       return 0;
 
-    if (ndatalen > 0)
+    if (ndatalen > 0) {
       Consume(&v, &c, ndatalen);
+      stream->Commit(ndatalen);
+    }
 
     dest.Realloc(nwrite);
     sendbuf_.Push(std::move(dest));
@@ -919,9 +922,6 @@ int QuicSession::Send0RTTStreamData(
       break;
   }
 
-  // Advance the read head of the source buffer
-  stream->Commit(count);
-
   return 0;
 }
 
@@ -942,7 +942,7 @@ int QuicSession::SendStreamData(QuicStream* stream) {
     return 0;
 
   std::vector<ngtcp2_vec> vec;
-  size_t count = stream->DrainInto(&vec);
+  stream->DrainInto(&vec);
 
   size_t c = vec.size();
   ngtcp2_vec* v = vec.data();
@@ -982,8 +982,10 @@ int QuicSession::SendStreamData(QuicStream* stream) {
     if (nwrite == 0)
       return 0;
 
-    if (ndatalen > 0)
+    if (ndatalen > 0) {
       Consume(&v, &c, ndatalen);
+      stream->Commit(ndatalen);
+    }
 
     dest.Realloc(nwrite);
     sendbuf_.Push(std::move(dest));
@@ -994,9 +996,6 @@ int QuicSession::SendStreamData(QuicStream* stream) {
       break;
   }
 
-  // Advance the read head of the source buffer
-  stream->Commit(count);
-
   return 0;
 }
 
diff --git a/src/node_quic_session.h b/src/node_quic_session.h
index b661bbd599..6cba54fbe8 100644
--- a/src/node_quic_session.h
+++ b/src/node_quic_session.h
@@ -294,7 +294,6 @@ class QuicSession : public AsyncWrap,
   inline void DecrementAllocatedSize(size_t size) override;
 
  private:
-
   // Returns true if the QuicSession has entered the
   // closing period following a call to ImmediateClose.
   // While true, the QuicSession is only permitted to
diff --git a/src/node_quic_socket.cc b/src/node_quic_socket.cc
index 2b8ff2e9f8..907a5bd02b 100644
--- a/src/node_quic_socket.cc
+++ b/src/node_quic_socket.cc
@@ -575,7 +575,7 @@ int QuicSocket::DropMembership(const char* address, const char* iface) {
 int QuicSocket::SendPacket(
     SocketAddress* dest,
     std::shared_ptr<QuicBuffer> buffer) {
-  if (buffer->Length() == 0 || buffer->ReadRemaining() == 0)
+  if (buffer->Length() == 0)
     return 0;
   char* host;
   SocketAddress::GetAddress(**dest, &host);
@@ -586,7 +586,7 @@ int QuicSocket::SendPacket(
 int QuicSocket::SendPacket(
     const sockaddr* dest,
     std::shared_ptr<QuicBuffer> buffer) {
-  if (buffer->Length() == 0 || buffer->ReadRemaining() == 0)
+  if (buffer->Length() == 0)
     return 0;
   char* host;
   SocketAddress::GetAddress(dest, &host);
@@ -704,16 +704,17 @@ void QuicSocket::SendWrap::OnSend(
 int QuicSocket::SendWrap::Send() {
   std::vector<uv_buf_t> vec;
   if (auto buf = buffer_.lock()) {
-    size_t len = buf->DrainInto(&vec, &length_);
-    if (len == 0) return 0;
-    Debug(socket_, "Sending %llu bytes (%d buffers of %d remaining)",
-          length_, len, buf->ReadRemaining());
+    size_t length = buf->DrainInto(&vec);
+    if (length == 0) return 0;
+    Debug(socket_,
+          "Sending %llu bytes (%d buffers)",
+          length, vec.size());
     if (socket_->IsDiagnosticPacketLoss(socket_->tx_loss_)) {
       Debug(socket_, "Simulating transmitted packet loss.");
       // Advance even though we're not actually sending. This
       // way the local code continues to act as if a write
       // occurred.
-      buf->SeekHead(len);
+      buf->Consume(length);
       OnSend(&req_, 0);
       return 0;
     }
@@ -726,7 +727,7 @@ int QuicSocket::SendWrap::Send() {
         OnSend);
     // If sending was successful, advance the read head
     if (err == 0)
-      buf->SeekHead(len);
+      buf->Consume(length);
     return err;
   }
   return -1;
diff --git a/src/node_quic_stream.cc b/src/node_quic_stream.cc
index 506ef18aa9..d2f2619666 100644
--- a/src/node_quic_stream.cc
+++ b/src/node_quic_stream.cc
@@ -282,9 +282,18 @@ int QuicStream::DoWrite(
   // to be careful not to allow the internal buffer to grow
   // too large, or we'll run into several other problems.
 
-  uint64_t len = streambuf_.Copy(bufs, nbufs);
-  IncrementStat(len, &stream_stats_, &stream_stats::bytes_sent);
-  req_wrap->Done(0);
+  uint64_t length =
+      streambuf_.Push(
+          bufs,
+          nbufs,
+          [](int status, void* user_data){
+            WriteWrap* req_wrap = static_cast<WriteWrap*>(user_data);
+            req_wrap->Done(status);
+          },
+          req_wrap,
+          req_wrap->object());
+
+  IncrementStat(length, &stream_stats_, &stream_stats::bytes_sent);
   stream_stats_.stream_sent_at = uv_hrtime();
   session_->SendStreamData(this);
 
@@ -295,25 +304,12 @@ int QuicStream::DoWrite(
 void QuicStream::AckedDataOffset(uint64_t offset,  size_t datalen) {
   if (IsDestroyed())
     return;
-  streambuf_.Consume(datalen);
 
   uint64_t now = uv_hrtime();
   if (stream_stats_.stream_acked_at > 0)
     data_rx_ack_.Record(now - stream_stats_.stream_acked_at);
   stream_stats_.stream_acked_at = now;
   data_rx_acksize_.Record(datalen);
-
-  // TODO(@jasnell): One possible DOS attack vector is a peer that sends
-  // very small acks at a rate that is just fast enough not to run afoul
-  // of the idle timeout. This can force a QuicStream to hold on to
-  // buffered data for long periods of time, eating up resources. The
-  // data_rx_ack_ and data_rx_acksize_ histograms can be used to detect
-  // this behavior. There are, however, legitimate reasons why a peer
-  // would send small acks at a slow rate, so there are no blanket rules
-  // that we can apply to this. We need to determine a reasonable default
-  // that can be overriden by user code. When the activity falls below
-  // that threshold, we will emit an event that the user code can respond
-  // to.
 }
 
 size_t QuicStream::DrainInto(
@@ -321,8 +317,8 @@ size_t QuicStream::DrainInto(
   return streambuf_.DrainInto(vec);
 }
 
-void QuicStream::Commit(size_t count) {
-  streambuf_.SeekHead(count);
+void QuicStream::Commit(uint64_t length) {
+  streambuf_.Consume(length);
 }
 
 inline void QuicStream::IncrementAvailableOutboundLength(size_t amount) {
@@ -513,7 +509,7 @@ void QuicStreamShutdown(const FunctionCallbackInfo<Value>& args) {
   stream->Session()->ShutdownStream(
       stream->GetID(),
       family == QUIC_ERROR_APPLICATION ? code : 0);
- }
+}
 }  // namespace
 
 void QuicStream::Initialize(
diff --git a/src/node_quic_stream.h b/src/node_quic_stream.h
index a5d084e9c0..7a3be310c1 100644
--- a/src/node_quic_stream.h
+++ b/src/node_quic_stream.h
@@ -185,7 +185,7 @@ class QuicStream : public AsyncWrap,
   size_t DrainInto(
     std::vector<ngtcp2_vec>* vec);
 
-  void Commit(size_t count);
+  void Commit(uint64_t length);
 
   AsyncWrap* GetAsyncWrap() override { return this; }
 
diff --git a/test/cctest/test_quic_buffer.cc b/test/cctest/test_quic_buffer.cc
index 98bb82bba0..23ed52623e 100644
--- a/test/cctest/test_quic_buffer.cc
+++ b/test/cctest/test_quic_buffer.cc
@@ -44,23 +44,21 @@ TEST(QuicBuffer, Simple) {
 
   QuicBuffer buffer;
   buffer.Push(&buf, 1, [&](int status, void* user_data) {
-    EXPECT_EQ(&test, user_data);
-    EXPECT_EQ(0, status);
+    EXPECT_EQ(user_data, &test);
+    EXPECT_EQ(status, 0);
     done = true;
   }, &test);
+  CHECK_EQ(buffer.Length(), 100);
+  CHECK_EQ(buffer.Size(), 1);
 
   buffer.Consume(100);
-  CHECK_EQ(100, buffer.Length());
-  CHECK_EQ(1, buffer.Size());
+  CHECK_EQ(buffer.Length(), 0);
+  CHECK_EQ(buffer.Size(), 0);
 
-  // We have to move the read head forward in order to consume
-  buffer.SeekHead(1);
-  buffer.Consume(100);
-  CHECK_EQ(0, buffer.Length());
-  CHECK_EQ(0, buffer.Size());
-  CHECK_EQ(true, done);
+  CHECK_EQ(done, true);
 }
 
+
 TEST(QuicBuffer, ConsumeMore) {
   char data[100];
   memset(&data, 0, node::arraysize(data));
@@ -71,16 +69,18 @@ TEST(QuicBuffer, ConsumeMore) {
 
   QuicBuffer buffer;
   buffer.Push(&buf, 1, [&](int status, void* user_data) {
-    EXPECT_EQ(&test, user_data);
-    EXPECT_EQ(0, status);
+    EXPECT_EQ(user_data, &test);
+    EXPECT_EQ(status, 0);
     done = true;
   }, &test);
+  CHECK_EQ(buffer.Length(), 100);
+  CHECK_EQ(buffer.Size(), 1);
 
-  buffer.SeekHead();
   buffer.Consume(150);  // Consume more than what was buffered
-  CHECK_EQ(true, done);
-  CHECK_EQ(0, buffer.Length());
-  CHECK_EQ(0, buffer.Size());
+
+  CHECK_EQ(done, true);
+  CHECK_EQ(buffer.Length(), 0);
+  CHECK_EQ(buffer.Size(), 0);
 }
 
 TEST(QuicBuffer, Multiple) {
@@ -97,13 +97,12 @@ TEST(QuicBuffer, Multiple) {
     uv_buf_t b = buf1.ToUVBuf();
     buffer.Push(&b, 1, cb, &buf1);
   }
+
   {
     uv_buf_t b = buf2.ToUVBuf();
     buffer.Push(&b, 1, cb, &buf2);
   }
 
-  buffer.SeekHead(2);
-
   buffer.Consume(25);
   CHECK_EQ(125, buffer.Length());
   CHECK_EQ(2, buffer.Size());
@@ -140,7 +139,6 @@ TEST(QuicBuffer, Multiple2) {
     CHECK_EQ(ptr, data);
     delete data;
   }, ptr);
-  buffer.SeekHead(node::arraysize(bufs));
 
   buffer.Consume(25);
   CHECK_EQ(2, buffer.Size());
@@ -182,7 +180,6 @@ TEST(QuicBuffer, Cancel) {
     delete data;
   }, ptr);
 
-  buffer.SeekHead();
   buffer.Consume(25);
   CHECK_EQ(2, buffer.Size());
   CHECK_EQ(75, buffer.Length());
@@ -216,8 +213,6 @@ TEST(QuicBuffer, Multiple3) {
   CHECK_EQ(150, buffer.Length());
   CHECK_EQ(2, buffer.Size());
 
-  buffer.SeekHead(2);
-
   buffer.Consume(25);
   CHECK_EQ(125, buffer.Length());
   CHECK_EQ(2, buffer.Size());
@@ -234,7 +229,6 @@ TEST(QuicBuffer, Multiple3) {
   CHECK_EQ(75, buffer.Length());
   CHECK_EQ(2, buffer.Size());
 
-  buffer.SeekHead();
   buffer.Consume(75);
   CHECK_EQ(0, buffer.Length());
   CHECK_EQ(0, buffer.Size());
@@ -306,9 +300,8 @@ TEST(QuicBuffer, MallocedBuffer) {
   CHECK_EQ(100, buffer.Length());
 
   std::vector<uv_buf_t> vec;
-  size_t len = buffer.DrainInto(&vec);
+  buffer.DrainInto(&vec);
   CHECK_EQ(1, vec.size());
-  buffer.SeekHead(len);
 
   buffer.Consume(50);
   CHECK_EQ(1, buffer.Size());
@@ -320,43 +313,3 @@ TEST(QuicBuffer, MallocedBuffer) {
   CHECK_EQ(0, buffer.Length());
   CHECK_EQ(1, count);
 }
-
-TEST(QuicBuffer, Head) {
-  uint8_t* data = node::Malloc<uint8_t>(100);
-  memset(data, 0, 100);
-  QuicBuffer buffer;
-  buffer.Push(node::MallocedBuffer<uint8_t>(data, 100));
-  CHECK_EQ(1, buffer.Size());
-
-  // buffer.Head() returns the current read head
-  {
-    uv_buf_t buf = buffer.Head();
-    CHECK_EQ(100, buf.len);
-    CHECK_EQ(0, buf.base[0]);
-  }
-
-  buffer.Consume(50);
-  CHECK_EQ(1, buffer.Size());
-
-  {
-    uv_buf_t buf = buffer.Head();
-    CHECK_EQ(100, buf.len);
-    CHECK_EQ(0, buf.base[0]);
-  }
-
-  // Seeking the head to the end will
-  // result in an empty head
-  buffer.SeekHead();
-  {
-    uv_buf_t buf = buffer.Head();
-    CHECK_EQ(0, buf.len);
-    CHECK_EQ(nullptr, buf.base);
-  }
-  // But the buffer will still have unconsumed data
-  CHECK_EQ(100, buffer.Length());
-  CHECK_EQ(1, buffer.Size());
-
-  buffer.Consume(100);
-  CHECK_EQ(0, buffer.Length());
-  CHECK_EQ(0, buffer.Size());
-}
diff --git a/test/parallel/test-quic-stream-close-early.js b/test/parallel/test-quic-stream-close-early.js
index 886b2f8e47..7359e3950b 100644
--- a/test/parallel/test-quic-stream-close-early.js
+++ b/test/parallel/test-quic-stream-close-early.js
@@ -40,25 +40,17 @@ server.on('session', common.mustCall((session) => {
   session.on('secure', common.mustCall((servername, alpn, cipher) => {
     const uni = session.openStream({ halfOpen: true });
     uni.write('hi');
-    uni.close(2);
+    uni.close(3);
 
     uni.on('abort', common.mustCall((code, finalSize) => {
-      // TODO(@jasnell): Code is currently 0 for some reason..
-      // need to investigate
-      // assert.strictEqual(code, 2);
-      assert.strictEqual(finalSize, 0);
+      assert.strictEqual(code, 3);
+      assert.strictEqual(finalSize, 2);
     }));
 
-    // End will be called because the writable side is closed before
-    // close is event called. The data event will never be emitted.
+
     uni.on('data', common.mustNotCall());
     uni.on('end', common.mustCall());
-
-    // Finish will not emitted because the stream is closed abruptly
-    // before the stream can complete.
-    uni.on('finish', common.mustNotCall());
-
-    // The close event will always emit, however
+    uni.on('finish', common.mustCall());
     uni.on('close', common.mustCall());
 
     debug('Unidirectional, Server-initiated stream %d opened', uni.id);
@@ -68,19 +60,17 @@ server.on('session', common.mustCall((session) => {
     debug('Bidirectional, Client-initiated stream %d received', stream.id);
     stream.write('hello there');
 
-    stream.on('abort', common.mustCall((code, finalSize) => {
-      debug('Bidirectional, Client-initiated stream %d aborted', stream.id);
+    stream.on('abort', common.mustNotCall());
+
+    stream.resume();
+    stream.on('end', common.mustCall(() => {
+      const { code, finalSize } = stream.resetReceived;
       assert.strictEqual(code, 1);
-      assert.strictEqual(finalSize, 5);  // The client sent 'hello'
+      assert.strictEqual(finalSize, 5);
+      stream.end();
     }));
-
-    // Because the stream ended abruptly, abort is emitted but end and
-    // finish are not.
-    stream.on('end', common.mustNotCall());
-    stream.on('finish', common.mustNotCall());
-
-    // Close is always emitted, however.
     stream.on('close', common.mustCall());
+    stream.on('finish', common.mustCall());
   }));
 
   session.on('close', common.mustCall());
@@ -120,11 +110,9 @@ server.on('ready', common.mustCall(() => {
       assert.strict(finalSize, 11); // The server sent 'hello there'
     }));
 
-    // Finish and end are not called because the stream has closed abruptly
-    // before the stream was finished.
-    stream.on('finish', common.mustNotCall());
-    stream.on('end', common.mustNotCall());
-
+    stream.resume();
+    stream.on('finish', common.mustCall());
+    stream.on('end', common.mustCall());
     stream.on('close', common.mustCall(() => {
       debug('Bidirectional, Client-initiated stream %d closed', stream.id);
       countdown.dec();
@@ -135,21 +123,19 @@ server.on('ready', common.mustCall(() => {
 
   req.on('stream', common.mustCall((stream) => {
     debug('Unidirectional, Server-initiated stream %d received', stream.id);
+    assert(!stream.writable);
 
-    stream.on('abort', common.mustCall((code, finalSize) => {
-      debug('Unidirectional, Server-initiated stream %d aborted', stream.id);
-      assert.strictEqual(code, 2);
+    stream.resume();
+    stream.on('abort', common.mustNotCall());
+    stream.on('data', common.mustCall());
+    stream.on('end', common.mustCall(() => {
+      const { code, finalSize } = stream.resetReceived;
+      assert.strictEqual(code, 3);
       assert.strictEqual(finalSize, 2);
+      stream.end();
     }));
+    stream.on('finish', common.mustNotCall());
 
-    // The data event will be emitted once...
-    stream.on('data', common.mustCall());
-
-    // But because the stream has been closed abruptly, the abort event
-    // will be emitted and end will never emit.
-    stream.on('end', common.mustNotCall());
-
-    // The close event will always emit.
     stream.on('close', common.mustCall(() => {
       debug('Unidirectional, Server-initiated stream %d closed', stream.id);
       countdown.dec();
-- 
2.21.0.windows.1

```

**Comment by jasnell** [comment]
landed... will keep iterating in a new PR

**Pull request closed without merging**
