### PR TITLE
doc: add `--experimental-quic` in the doc

### PR DESCRIPTION
**Pull request by trivikr**
Refs: https://github.com/nodejs/quic/issues/174
Refs: https://github.com/nodejs/quic/pull/83

##### Checklist

- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by jasnell** [comment]
Currently the build flag does not gate the modifications to openssl but I actually want them to. The reason I went with a build flag for now is so we can land in master soon without worrying too much about the still in flux changes to the openssl patches and the addition of the two new dependency libraries. There's also the long standing and still unresolved question about whether or not it is ok to introduce new unscoped top level modules (e.g. `require('quic')`) and the fact that a module called `quic` already exists in npm. Because of all that, I figured a build flag was generally safer for now. The goal would be to remove the flag as soon as possible and not even require a runtime flag, just have `require('quic')` emit the experimental warning while it is still experimental.

**Comment by jasnell** [comment]
Rather than make this change, could we create a pinned issue that includes the build instructions?

**Comment by trivikr** [comment]
> I assume the idea is that this will not be merged into the main repo when the PR is opened?

Yup, the idea is to revert this change before merging with Node.js core

> Rather than make this change, could we create a pinned issue that includes the build instructions?

+1 for creating a pinned issue

**Comment by trivikr** [comment]
A pinned issue was created at https://github.com/nodejs/quic/issues/183

**Pull request closed without merging**
