### PR TITLE
quic: move setting handle owner_symbol after destroy

### PR DESCRIPTION
**Pull request by danbev**
Currently, when QuicStream._destroy calls handle.destroy() the following
error is thrown:
```console
internal/stream_base_commons.js:76
  if (stream.destroyed) {
             ^

TypeError: Cannot read property 'destroyed' of undefined
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:76:14)
    at QuicStream._destroy (internal/quic/core.js:1437:14)
    at QuicStream.destroy (internal/streams/destroy.js:37:8)
    at QuicClientSession.destroy (internal/quic/core.js:1008:14)
    at QuicClientSession.onSessionClose (internal/quic/core.js:212:22)
```
This commit moves the setting of the owner_symbol to after the destroy
call.

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by jasnell** [comment]
LGTM... although I believe I've got this one covered in the current open PR

**Comment by jasnell** [comment]
(not the exact same fix, but the underlying bits that were causing it to fail)

**Comment by danbev** [comment]
> LGTM... although I believe I've got this one covered in the current open PR

I only noticed this when running the code from that PR, but I might be wrong. If that is the case we can just close this.

**Comment by jasnell** [comment]
Ah! Awesome :-) Really appreciate you taking a look at that one :-)

**Comment by jasnell** [comment]
Would you mind if I just pull this commit into that other PR?

**Comment by appden** [comment]
This change seems to already be present in `iteration-6`, but I'm curious if a similar change should be made to `QuicSocket` and `QuicSession` as well?

**Comment by jasnell** [comment]
> but I'm curious if a similar change should be made to QuicSocket and QuicSession as well?

Probably :-)

**Comment by danbev** [comment]
>Would you mind if I just pull this commit into that other PR?

No problems at all.

**Comment by danbev** [comment]
Sorry, this is indeed fixed on the iteration-6 PR/branch.

**Pull request closed without merging**
