### PR TITLE
quic: use a unique-ptr for Timer

### PR DESCRIPTION
**Pull request by jasnell**
Alternative to https://github.com/nodejs/quic/pull/100

/cc @danbev

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by danbev** [comment]
I'm sure I'm missing something here, but I don't see the need to do any memory clean up apart from what is done by the unique_ptr, which will clean up the Timer instance when the QuicSession destructor is called. 

`uv_timer` is not a pointer in Timer class:
```console
(lldb) fr v timer->timer_
(uv_timer_t) timer->timer_ = {
  data = 0x0000000000000000
  loop = 0x00000001029f9170
  type = UV_TIMER
  close_cb = 0x0000000000000000
  handle_queue = ([0] = 0x00000001029f9180, [1] = 0x0000000104f420f0)
  u = {
    fd = 0
    reserved = ([0] = 0x0000000000000000, [1] = 0x0000000000000001, [2] = 0x0000000000000000, [3] = 0x0000000000000000)
  }
  next_closing = 0x0000000000000000
  flags = 8
  timer_cb = 0x0000000000000000
  heap_node = ([0] = 0x0000000000000000, [1] = 0x0000000000000000, [2] = 0x0000000000000000)
  timeout = 0
  repeat = 0
  start_id = 0
}
```
When the the callback registered in `Timer::Free` is called, it will try to delete something that has not been allocated leading to the following error:
```console
node(31513,0x104c3c5c0) malloc: *** error for object 0x10690bbd0: pointer being freed was not allocated
node(31513,0x104c3c5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by jasnell** [comment]
doh, you're right, freed the wrong thing ;-) ... The issue here is that the uv_timer_t handle needs to be closed when it is deconstructed, and that does not necessarily happen synchronously. Instead of freeing the uv_timer_t tho, I needed to free the Timer itself in the callback. Will update the PR in a minute

**Comment by danbev** [comment]
> The issue here is that the uv_timer_t handle needs to be closed when it is deconstructed, and that does not necessarily happen synchronously

Ah I see, thanks for clarifying that!

**Comment by danbev** [comment]
Landed in 362d112b389250c97c6e6f2c6d58305b2347d6f1.

**Pull request closed without merging**
