### PR TITLE
quic: make alpn default to quic.alpnVersion

### PR DESCRIPTION
**Pull request by danbev**
Currently, in `doc/api/quic.md` the first quic server example does not
show the `alpn` option being passed to the listen function. There is an
explicit check in core.js where this option is checked and invalid type
error will be thrown if it not specified, or not of type string.

This commit suggests defaulting to the `alpnVersion()` if the `alpn` option is
not specified.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by danbev** [comment]
Hmm, the name `alpnVersion` should probably be changed to `alpnProtocolIdentifier` or something like that. I'm guilty of this and not sure what my reasoning was behind that name :(

**Comment by jasnell** [comment]
Does this need to be a function? Could it be set as a string constant?

**Comment by danbev** [comment]
> Does this need to be a function? Could it be set as a string constant?

Yeah, I think it can be a constant. I got caught up in trying to get manually test (client/server) for this yesterday and I'm off today but I'll take another look at this tomorrow. 

BTW, do you have a working client and server example? I believe that the `test-quic-client-server.js` test is not currently working, is that correct?

**Comment by jasnell** [comment]
Sorry, just spotted the question in the last comment, `test-quic-client-server` should be working. It is, at least, for me on Windows and Ubuntu.

**Comment by danbev** [comment]
> Sorry, just spotted the question in the last comment, `test-quic-client-server` should be working. It is, at least, for me on Windows and Ubuntu.

No worries! I'm on a mac so perhaps this is specific to it, I'll take another stab at this tomorrow and try to figure out what is wrong (the tests timeout when run using test.py, or just hang when run manually. It's like the `secure` callback is never called or something).

**Comment by danbev** [comment]
> I’d be okay with landing this, although converting this to a constant exposed on the binding would also be nice :)

Sorry about the delay on this! I've been trying to figure out why there are test failure for me (I'm on macosx) and I've not been able to actually test the changes I've made. I hope to continue looking into this later today and tomorrow. 

These are the test failure that I'm seeing at the moment:
<details>
<summary>test failures</summary>

```console
=== release test-process-external-stdio-close ===
Path: parallel/test-process-external-stdio-close
assert.js:89
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

1 !== 0

    at ChildProcess.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-process-external-stdio-close.js:20:12)
    at ChildProcess.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/common/index.js:372:15)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1028:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:209:13)
    at Pipe.<anonymous> (net.js:588:12) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-process-external-stdio-close.js
=== release test-process-external-stdio-close-spawn ===
Path: parallel/test-process-external-stdio-close-spawn
assert.js:89
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

1 !== 0

    at ChildProcess.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-process-external-stdio-close-spawn.js:25:12)
    at ChildProcess.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/common/index.js:372:15)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1028:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:209:13)
    at Pipe.<anonymous> (net.js:588:12) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 0,
  operator: 'strictEqual'
}
Command: out/Release/node /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-process-external-stdio-close-spawn.js
=== release test-quic-client-server ===
Path: parallel/test-quic-client-server
(node:40152) internal/test/binding: These APIs are for internal testing only. Do not use them.
(node:40152) ExperimentalWarning: QUIC protocol support is experimental and not yet supported for production use
assert.js:89
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== 2

    at QuicClientSession.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-client-server.js:346:12)
    at QuicClientSession.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/common/index.js:372:15)
    at QuicClientSession.emit (events.js:209:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 0,
  expected: 2,
  operator: 'strictEqual'
}
Command: out/Release/node --expose-internals /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-client-server.js
=== release test-wrap-js-stream-exceptions ===
Path: parallel/test-wrap-js-stream-exceptions
assert.js:89
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Missing expected exception.
    at Object.<anonymous> (/Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-wrap-js-stream-exceptions.js:19:8)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:789:32)
    at Function.Module._load (internal/modules/cjs/loader.js:702:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: /Error: write EPROTO/,
  operator: 'throws'
}
Command: out/Release/node --expose-internals /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-wrap-js-stream-exceptions.js
=== release test-http2-reset-flood ===
Path: parallel/test-http2-reset-flood
Command: out/Release/node /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-http2-reset-flood.js
--- TIMEOUT ---
=== release test-quic-packetloss ===
Path: parallel/test-quic-packetloss
(node:40154) ExperimentalWarning: QUIC protocol support is experimental and not yet supported for production use
Command: out/Release/node --expose-internals /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-packetloss.js
--- TIMEOUT ---
=== release test-quic-stream-close-early ===
Path: parallel/test-quic-stream-close-early
(node:40159) ExperimentalWarning: QUIC protocol support is experimental and not yet supported for production use
Command: out/Release/node --expose-internals /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-stream-close-early.js
--- TIMEOUT ---
=== release test-quic-simple-client-migrate ===
Path: parallel/test-quic-simple-client-migrate
(node:40158) ExperimentalWarning: QUIC protocol support is experimental and not yet supported for production use
Command: out/Release/node --expose-internals /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-simple-client-migrate.js
--- TIMEOUT ---
=== release test-quic-stream-destroy ===
Path: parallel/test-quic-stream-destroy
(node:40160) ExperimentalWarning: QUIC protocol support is experimental and not yet supported for production use
Command: out/Release/node /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-stream-destroy.js
--- TIMEOUT ---
=== release test-quic-stream-identifiers ===
Path: parallel/test-quic-stream-identifiers
(node:40161) ExperimentalWarning: QUIC protocol support is experimental and not yet supported for production use
Command: out/Release/node /Users/danielbevenius/work/nodejs/quic/node_quic/test/parallel/test-quic-stream-identifiers.js
--- TIMEOUT ---
[04:07|% 100|+ 2622|-  10]: Done
 ```
</etails>

**Comment by addaleax** [comment]
Yeah, I’m seing the errors in non-QUIC tests too, plus the parallel/test-quic-client-server one intermittently (~ 5 % of the time). I’d wanted to wait for a rebase against nodejs/node before investigating the non-QUIC failures, because this repo is a bit out of date and I don’t want to put effort into solving something that might already be solved.

**Comment by danbev** [comment]
> Yeah, I’m seing the errors in non-QUIC tests too,

Ah good to know, I thought it was only me 😄 

> I’d wanted to wait for a rebase against nodejs/node before investigating the non-QUIC failures, because this repo is a bit out of date and I don’t want to put effort into solving something that might already be solved.

That makes sense for sure, I'll hold off a little as well. Thanks!

**Comment by jasnell** [comment]
Landed. I know the macos issue is still there but this change is looking good everywhere else and the failures don't seem to have anything to do with this change.

**Pull request closed without merging**
