### PR TITLE
Fix some clang-tidy issue

### PR DESCRIPTION
**Pull request by gengjiawen**
##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by gengjiawen** [comment]
Looks travis ci not setup for this Project ?
@danbev @richardlau

**Comment by richardlau** [comment]
It's something the organisation owners would have to enable.

**Comment by gengjiawen** [comment]
Looks current master failed on travis ci https://travis-ci.com/gengjiawen/quic/jobs/190876947. Build passed on my Windows though.
```console
In file included from ../src/node_quic_session.h:11:0,
                 from ../src/node_quic_session.cc:8:
../src/node_quic_util.h:23:44: error: ‘constexpr uint64_t node::quic::{anonymous}::operator""_k(uint64_t)’ has invalid argument list
 constexpr uint64_t operator"" _k(uint64_t k) {
                                            ^
../src/node_quic_util.h:27:44: error: ‘constexpr uint64_t node::quic::{anonymous}::operator""_m(uint64_t)’ has invalid argument list
 constexpr uint64_t operator"" _m(uint64_t m) {
                                            ^
../src/node_quic_util.h:31:44: error: ‘constexpr uint64_t node::quic::{anonymous}::operator""_g(uint64_t)’ has invalid argument list
 constexpr uint64_t operator"" _g(uint64_t g) {
                                            ^
../src/node_quic_util.h:43:55: error: unable to find numeric literal operator ‘operator""_k’
 constexpr size_t DEFAULT_MAX_STREAM_DATA_BIDI_LOCAL = 256_k;
                                                       ^~~~~
In file included from ../src/node_quic_session.cc:8:0:
../src/node_quic_session.h:51:42: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                          ^    
../src/node_quic_session.h:51:89: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                                                                         ^    
In file included from ../src/node_quic_session.cc:8:0:
../src/node_quic_session.h:51:128: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                                                                                                                ^    
../src/node_quic_session.h:51:156: error: unable to find numeric literal operator ‘operator""_m’
   QUICSESSION_CONFIG(V)
                                                                                                                                                            ^  
../src/node_quic_session.cc: In member function ‘void node::quic::QuicSessionConfig::ResetToDefaults()’:
../src/node_quic_session.cc:882:33: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                 ^    
../src/node_quic_session.cc:882:71: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                                                       ^    
../src/node_quic_session.cc:882:101: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                                                                                     ^    
../src/node_quic_session.cc:882:120: error: unable to find numeric literal operator ‘operator""_m’
   QUICSESSION_CONFIG(V)
                                                                                                                        ^  
node_lib.target.mk:354: recipe for target '/home/travis/build/gengjiawen/quic/out/Release/obj.target/node_lib/src/node_quic_session.o' failed
make[1]: *** [/home/travis/build/gengjiawen/quic/out/Release/obj.target/node_lib/src/node_quic_session.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../src/node_quic_session.h:11:0,
                 from ../src/node_quic_socket.h:9,
                 from ../src/node_quic_socket.cc:7:
../src/node_quic_util.h:23:44: error: ‘constexpr uint64_t node::quic::{anonymous}::operator""_k(uint64_t)’ has invalid argument list
 constexpr uint64_t operator"" _k(uint64_t k) {
                                            ^
../src/node_quic_util.h:27:44: error: ‘constexpr uint64_t node::quic::{anonymous}::operator""_m(uint64_t)’ has invalid argument list
 constexpr uint64_t operator"" _m(uint64_t m) {
                                            ^
../src/node_quic_util.h:31:44: error: ‘constexpr uint64_t node::quic::{anonymous}::operator""_g(uint64_t)’ has invalid argument list
 constexpr uint64_t operator"" _g(uint64_t g) {
                                            ^
../src/node_quic_util.h:43:55: error: unable to find numeric literal operator ‘operator""_k’
 constexpr size_t DEFAULT_MAX_STREAM_DATA_BIDI_LOCAL = 256_k;
                                                       ^~~~~
In file included from ../src/node_quic_socket.h:9:0,
                 from ../src/node_quic_socket.cc:7:
../src/node_quic_session.h:51:42: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                          ^    
../src/node_quic_session.h:51:89: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                                                                         ^    
In file included from ../src/node_quic_socket.h:9:0,
                 from ../src/node_quic_socket.cc:7:
../src/node_quic_session.h:51:128: error: unable to find numeric literal operator ‘operator""_k’
   QUICSESSION_CONFIG(V)
                                                                                                                                ^    
../src/node_quic_session.h:51:156: error: unable to find numeric literal operator ‘operator""_m’
   QUICSESSION_CONFIG(V)
                                                                                                                                                            ^  
node_lib.target.mk:354: recipe for target '/home/travis/build/gengjiawen/quic/out/Release/obj.target/node_lib/src/node_quic_socket.o' failed
make[1]: *** [/home/travis/build/gengjiawen/quic/out/Release/obj.target/node_lib/src/node_quic_socket.o] Error 1
rm 3dfbad2dc6e8cbfdceba0c12526d9c22a9096131.intermediate 3ccfefc47a714a03f9e7ef3bd2303781d23c2463.intermediate 5575e1de61d052dfe1c6de472181f1f35c32c98a.intermediate 2e2fca320e474cff84994a2881c78e56c5ce0913.intermediate
Makefile:99: recipe for target 'node' failed
make: *** [node] Error 2
The command "make -j2 V=" failed and exited with 2 during .
```

**Comment by jasnell** [comment]
Let's worry about the travis bit later. Seems to be working elsewhere.

**Comment by jasnell** [comment]
Landed

**Pull request closed without merging**
