### PR TITLE
deps: update ngtcp2 to latest draft-18

### PR DESCRIPTION
**Pull request by danbev**
This commit updates ngtcp2 to the current latest commit on the draft-18
branch.

Refs:
https://github.com/ngtcp2/ngtcp2/commit/e0222ba575e95875811704fac882feeb84c3be1e

##### Checklist

- [x] `make -j4 test-only` (UNIX), or `vcbuild test-only` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by jasnell** [comment]
Awesome! Thank you! I just about have a minimal server implemented with an initial take on the API.

**Comment by jasnell** [comment]
LGTM

**Comment by jasnell** [comment]
I'll get this landed by Friday. I'm working on a few bits now that'll likely change once this lands so I want to complete the thought before having to go back over it.

**Comment by danbev** [comment]
I should update this as there have been changes upstream. Turns out that I'm not working today, but I'd be happy to update on Monday.

**Comment by danbev** [comment]
I've updated to the latest commit on [ngtcp2/draft-18](https://github.com/ngtcp2/ngtcp2/commit/e0222ba575e95875811704fac882feeb84c3be1e) branch now.

**Comment by jasnell** [comment]
I'll get this landed on Saturday!

**Comment by jasnell** [comment]
I'm sorry @danbev .. I ended up completely sidetracked the past few days. Can I ask you to rebase this and I'll get it landed.

**Comment by danbev** [comment]
Closing this as there is a draft-19 out and I'll create a PR with that version instead.

**Pull request closed without merging**
