### PR TITLE
test: fix quicstream-close-early

### PR DESCRIPTION
**Pull request by danbev**
Currently this test fails with the following error:
```console
events.js:292 Uncaught Error: write ECANCELED
    at WriteWrap.onWriteComplete [as oncomplete]
(internal/stream_base_commons.js:94:16)
    at QuicStream.[kClose] (internal/quic/core.js:2712:19)
    at QuicStream.close (internal/quic/core.js:2964:17)
    at QuicClientSession.<anonymous>
(/quic/quic/test/parallel/test-quic-quicstream-close-early.js:86:12)
    at QuicClientSession.<anonymous>
(/quic/quic/test/common/index.js:363:15)
    at QuicClientSession.emit (events.js:315:20)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Emitted 'error' event on QuicStream instance at:
    at emitErrorNT (internal/streams/destroy.js:98:8)
    at errorOrDestroy (internal/streams/destroy.js:155:7)
    at onwriteError (_stream_writable.js:399:3)
    at onwrite (_stream_writable.js:429:7)
    at WriteWrap.onWriteComplete [as oncomplete]
(internal/stream_base_commons.js:96:12)
    at QuicStream.[kClose] (internal/quic/core.js:2712:19)
    [... lines matching original stack trace ...]
    at QuicClientSession.emit (events.js:315:20)
```
This commit moves the close calls to after the registration of the error
event listeners.

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by danbev** [comment]
The test failure on mac os looks unrelated to this PR:
```console
2020-04-28T14:31:49.0198130Z not ok 1277 parallel/test-inspector-connect-main-thread
2020-04-28T14:31:49.0210400Z   ---
2020-04-28T14:31:49.0210870Z   duration_ms: 0.540
2020-04-28T14:31:49.0211210Z   severity: crashed
2020-04-28T14:31:49.0212010Z   exitcode: -11
2020-04-28T14:31:49.0212750Z   stack: |-
2020-04-28T14:31:49.0213160Z     Skip child is done
2020-04-28T14:31:49.0213480Z     Message for a test
2020-04-28T14:31:49.0213800Z     Worker is done
2020-04-28T14:31:49.0214120Z     Message NodeWorker.enable was sent
2020-04-28T14:31:49.0214450Z     Message Debugger.enable was sent
2020-04-28T14:31:49.0214780Z     Message Runtime.enable was sent
2020-04-28T14:31:49.0215110Z     Message Debugger.setBreakpointByUrl was sent
2020-04-28T14:31:49.0215430Z     Message Debugger.evaluateOnCallFrame was sent
2020-04-28T14:31:49.0215750Z     Message Debugger.resume was sent
```
I've re-run the test to see if it crashes again.

**Comment by jasnell** [comment]
Ugh. Yeah, that's a flaky failure we've inherited from nodejs/node master

**Comment by jasnell** [comment]
And re: this fix... the error handler shouldn't need to be registered first so will definitely investigate that.

**Comment by danbev** [comment]
Landed in c408e8dac791d8360707510d63c000b3a8098521.

**Pull request closed without merging**
